{% set version = '0.6-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fancova
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fANCOVA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fANCOVA/fANCOVA_{{ version }}.tar.gz
  sha256: c3ea3640d9a87abbfeae713141d606ece93bc88b9952f41a37b3f1fbe802bc12

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fANCOVA')"           # [not win]
    - "\"%R%\" -e \"library('fANCOVA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fANCOVA
  license: GPL-3.0-only
  summary: A collection of R functions to perform nonparametric analysis of covariance for regression
    curves or surfaces. Testing the equality or parallelism of nonparametric curves
    or surfaces is equivalent to analysis of variance (ANOVA) or analysis of covariance
    (ANCOVA) for one-sample functional data. Three different testing methods are available
    in the package, including one based on L-2 distance, one based on an ANOVA statistic,
    and one based on variance estimators.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
